FROM php:8.4-fpm-alpine

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions

RUN apk add --no-cache \
    ca-certificates \
    nginx \
    supervisor

RUN install-php-extensions pdo_pgsql intl opcache
